apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: surya-auth:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          envFrom:
            - configMapRef:
                name: mongo-config
            - secretRef:
                name: mongo-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort   # ✅ PENTING
  selector:
    app: auth
  ports:
    - port: 5050
      targetPort: 5050